version: 0.18.{build}

image: Visual Studio 2015

clone_folder: c:\projects\ivo

clone_depth: 1

platform: x86

configuration: Release

install:
#install and build assimp
  - cd c:\projects
  - git clone https://github.com/assimp/assimp.git
  - cd assimp
  - git reset --hard a8673d4828df5107186f49e5e4efa5316b727482
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015" -DASSIMP_BUILD_TESTS=OFF ..
  - cmake --build .
  - copy .\code\debug\*.* .\code\
#install glm
  - cd c:\projects
  - git clone https://github.com/g-truc/glm.git
  - cd glm
  - git reset --hard ad744735f66359b6aecdfe75e93c024f0c7ec055
#done
  - cd c:\projects\ivo

before_build:
  - set CMAKE_PREFIX_PATH=C:\Qt\5.9.2\msvc2015\
  - cmake -G "Visual Studio 14 2015" -Dassimp_ROOT="c:/projects/assimp" -Dglm_ROOT="c:/projects/glm"

build:
  parallel: true
  project: Ivo.sln
  verbosity: normal