language: c++

sudo: required
dist: trusty
group: deprecated-2017Q4

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
  - sudo apt-get update
  - sudo apt-get install mesa-common-dev
  - sudo apt-get install libgl1-mesa-dev
  - sudo apt-get install qt59-meta-full
  - sudo apt-get install libassimp-dev
  - git clone https://github.com/g-truc/glm.git
  - cd glm
  - git reset --hard ad744735f66359b6aecdfe75e93c024f0c7ec055
  - cmake -G "Unix Makefiles" && sudo make install && cd ..
  - git clone https://github.com/seriousalexej/TabToolbar.git
  - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
  - source $QT_ENV_SCRIPT
  - cd TabToolbar
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .. && sudo make install && cd ../..

script:
  - cmake -DCMAKE_BUILD_TYPE=Release ./src && cmake --build .